# 67. INTRODUCCION A LAS LISTAS 

## Lista 

La primera estructura de datos que veremos son las listas. Estas son un conjunto de elementos ordenados separados por comas y escritos entre claudator, $\textbf{[]}$. 

La listas son: 

* $\textbf{Heterogéneas}$: los elementos pueden ser de distinto tipo en una misma lista.
* $\textbf{Mutables}$: los elementos pueden ser modificados.

Un ejemplo de lista sería 

In [1]:
l = ["Juan", 31, 172.32, True]
print(l)

['Juan', 31, 172.32, True]


### Tamaño de una lista 

Para saber la longitud o el tamaño de una lista, podemos hacer uso de la función $\textbf{len()}$. 



In [2]:
l = [1,2,3,4,5,6,7]
len(l)

7

In [ ]:
l = ["Zoe", "Miguel", "Silvia", "Pablo"] #el primer elemento esta en la posicion 0. 
len(l)

# 68. Elementos de una lista 

Cada elemento en la lista tiene su propio indice 

In [4]:
names = ["Maria", "Juan", "Claudia", "Jorge", "Avelina"]

A María le corresponde el índice 0, a Juan el 1, etc. 

Cuidado. Los indices siempre empiezan en 0. De este modo, al primer elemetno le corresponde el indice 0; l segundo, el indice 1, etc. 

In [5]:
print(names[0])

Maria


In [6]:
print(names[2])

Claudia


In [7]:
print(names[4])

Avelina


In [8]:
print(names[-1]) #Ultimo elemento 

Avelina


In [9]:
print(names[-3]) #Tercer elemento empezando por el final  


Claudia


para acceder a varios elementos a la vez, podemos hacer uso de la función: 

In [10]:
print(names[2:4])

['Claudia', 'Jorge']


In [11]:
print(names[:3])

['Maria', 'Juan', 'Claudia']


In [12]:
print(names[3:])

['Jorge', 'Avelina']


Observacion. En cuanto a la función : 

* El indice indicado a la derecha de los : nunca es incluido 
* Si no indicamos elemento a la izquierda de los :, por defecto Python intepreta que se trata del 0. 
* Si no indicamos elemento a la derecha, por defecto python intepreta que debe de mostrar los elementos desde el indice indicando a la izquierda hasta el último. 

Además de acceder, podemos modificar los elementos de una lista. 

In [13]:
names[0] = "Marina"
names[3] = "Jaime"
names

['Marina', 'Juan', 'Claudia', 'Jaime', 'Avelina']

Podemos añadir nuevos elementos a una lista con el método .append()

In [14]:
names = ["Maria", "Cristina", "Juana"]
print(names)

names.append("Andrea")
print(names)
names.append("Ana")
print(names)

['Maria', 'Cristina', 'Juana']
['Maria', 'Cristina', 'Juana', 'Andrea']
['Maria', 'Cristina', 'Juana', 'Andrea', 'Ana']


Observacion. Los elementos añadidos con append se incluyen al final. 

Con insert() especificamos la posición donde queremos añadir el elemento, al primero le indicamos el indice donde queremos posicionar el nuevo elemento y en segundo lugar, indicamos dicho nuevo elemento. 

In [15]:
names = ["Mario", "Cristian", "Juan"]
print(names)

names.insert(1, "Andres")
print(names)
names.insert(3, "Miguel")
print(names)

['Mario', 'Cristian', 'Juan']
['Mario', 'Andres', 'Cristian', 'Juan']
['Mario', 'Andres', 'Cristian', 'Miguel', 'Juan']


# 69. EJERCICIO : AÑADIENDO POR TECLADO A UNA LISTA 

Vamos a pedirle al usuario la longitud de una lista y haremos que introduzca por teclado tanto número enteros como haya indicado, que se guardarán en una lista. Al acabar, imprimiremos la lista. 

In [1]:
n = int(input("Introduce el tamaño de la lista: "))
l = []

for i in range(n): 
    l.append(int(input()))
    
print("Tu lista es", l)

Introduce el tamaño de la lista: 9
9
9
9
9
9
9
9
9
9
Tu lista es 1


# 70. BUCLES CON LISTAS 

Si quisiéramos imprimir por pantalla todos los elementos de una lista, lo podríamos hacer mediante los índices 

In [2]:
names = ["Mario", "Cristian", "Juan"]
for i in range(len(names)):
    print(names[i])

Mario
Cristian
Juan


Mas facilmente iterando la lista con un for con la siguiente sintaxis:

In [3]:

for i in names:
    print(i)

Mario
Cristian
Juan


# 71. CONCATENACIÓN  Y REPETICIÓN DE LISTAS 

Dadas dos o más listas, podemos concetenarlas haciendo uso de la función + 

In [4]:
l1 = [True, 21, "Marta"]
l2 = [22.5, False, 22, "Rafa"]
print(l1 + l2)

[True, 21, 'Marta', 22.5, False, 22, 'Rafa']


## Repetición de listas 

Podemos repetir una misma lista tantas veces como queramos con la función * 

In [6]:
abc = ["A", "B", "C"]
print(abc * 5)

['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C']


## Mas métodos de listas 

El metodo $\textbf{count()}$ recibe un elemento como argumento y cuenta la cantidad de veces que aparece en la lista 

# 72. LISTAS ANIDADAS

Las listas anidadas son listas dentro de listas. Es decir, las listas no solo pueden contener números, strings o datos booleanos, sino que también pueden contener otras listas. 

Ejemplo 1 

A continuación mostramos una lista anidada, pues consta de 3 elementos: 

* 1 lista de 3 strings 
* 1 lista heterogénea de 3 elementos que a su vez contiene una lista con 5 números 
* 1 número 

In [7]:
l = [["María", "Santos", "Fernández"], 
     ["Juan", [1,2,3,4,5], 32],
     2]

Para acceder a un elemento, necesitamos su índice. Si un elemento está en una lista dentro de una lista dentro de una lista, en primer lugar indicamos el índice de la lista exterior dentro de []; después, el índice de la siguiente lista mas exterior tambien entre []; y por ultimo, el índice de la lista mas interna, claramente tambien entre []. 

Accedemos al string Fernández y luego al número 5. 

In [10]:
print(l[0][2]) #Fernandez
print(l[1][1][4])

Fernández
5


# 73. MAS METODOS DE LISTAS 

El metodo $\textbf{.count()}$ recibe un elemento como argumento y cuenta la cantidad de veces que aparece en la lista. 


In [14]:
numbers = [0, 1, 1, 2, 2, 2, 3, 3, 3, 3]

counted = []

for element in numbers:
    if element not in counted: 
        counted.append(element)
        print("El elemento {} aparece {} veces". format(element, numbers.count(element)))

El elemento 0 aparece 1 veces
El elemento 1 aparece 2 veces
El elemento 2 aparece 3 veces
El elemento 3 aparece 4 veces


In [15]:
counted

[0, 1, 2, 3]

In [17]:
numbers.count(2)

3

El metodo $\textbf{.extend()}$ extiende la lista agregando al final el iterable indicando el parámetro. 

In [18]:
numbers = [1, 2, 3, 4, 5]
print(numbers)
numbers.extend([6])
print(numbers)
numbers.extend([7, 8])
print(numbers)
numbers.extend(range(9, 16))
print(numbers)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


Observacion. Un iterable es un objeto de python capaz de devolver sus elemento uno por uno, permitiendo ser iterado en un bucle for. De momento solo conocemos las listas y el resultado de range(), pero en secciones futuras veremos los diccionarios, las tuplas y los connjuntos que tambien son objetos iterables. 

El metodo $\textbf{index()}$ recibe un elemento como argumento y devuelve el indice de la primera aparición en la lista. 

In [1]:
numbers = [0, 1, 1, 2, 2, 3, 4, 3, 4]
print(numbers.index(2))
print(numbers.index(4))

3
6


El metodo $\textbf{.pop()}$ devuelve el ultimo elemento de la lista y lo borra de la misma. 

In [3]:
print(numbers)
print(numbers.pop())
print(numbers)

[0, 1, 1, 2, 2, 3, 4, 3, 4]
4
[0, 1, 1, 2, 2, 3, 4, 3]


El metodo $\textbf{.remove()}$ recibe como argumento un elemento y borra su primera aparición de la lista. 

In [21]:
numbers = [0, 1, 2, 4, 3, 4, 5, 6, 7]
numbers.remove(4)
print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7]


El metodo $\textbf{.reverse()}$ devuelve la lista en orden inverso. 


In [22]:
numbers = [1, -1, 2, -2, 3, -3]
numbers.reverse()
print(numbers)

[-3, 3, -2, 2, -1, 1]


El metodo $\textbf{.sort()}$ devuelve la lista en orden. 

In [23]:
numbers = [1, 3, 5, 2, 4]
numbers.sort()
print(numbers)

[1, 2, 3, 4, 5]


Si quisieramos ordenar los elementos en orden decreciente, podríamos hacer uso del parámetro reverse del metodo .sort(): 

In [24]:
numbers = [1, 3, 5, 2, 4]
numbers.sort(reverse = True)
print(numbers)

[5, 4, 3, 2, 1]


Observacion. De momento solo conocemos las listas y el resultado de range(), pero en secicones furura veremos los diccionarios, las tuplas y los conjuntos, que también son objetos iterables. 

# 76. CONVERSION A LISTAS 

Para convertir un objeto itareble de python a lista, hay que usar la función list() 

In [27]:
 range(0, 100, 10) #tipo especial de dato, es una colección de valores

range(0, 100, 10)

In [29]:
type(range(0, 100, 10))

range

In [25]:
print(list(range(0, 100, 10)))

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]


In [34]:
print(type(list(range(0, 100, 10))))

<class 'list'>


# EJERCICIO : ELIMINANDO UN ELEMENTO DE INDICADO POR EL USUARIO. 

Dada una lista de caracteres, le pediremos al usuario que elemento quiere eliminar y lo eliminaremos de la lista. 

In [6]:
l = ["m","a","r","j","b","g","i","s","f","g"]
print("Esta es la lista original: {}".format(l))
c = input("Introduce el elemento que quieres eliminar: ")
for e in l:
    if e == c:
        l.remove(e)
    
print("Esta es la lista actualizada {}".format(l))

Esta es la lista original: ['m', 'a', 'r', 'j', 'b', 'g', 'i', 's', 'f', 'g']
Introduce el elemento que quieres eliminar: g
Esta es la lista actualizada ['m', 'a', 'r', 'j', 'b', 'i', 's', 'f']


# EJERCICIO: ORDENANDO ELEMENTOS DE UNA LISTA CREADA POR EL USUARIO. 

Vamos a pedir al usuario que ingrese 10 numero, los guardaremos en un alista y mostraremos la lista ordenada, siendo el usuario quien indique el orden: ascendente o descendente. 

In [7]:
reversed = bool(input("Si quieres orden descendente, escribe True. De lo contrario, dale a la tecla Enter: "))
l = []
for _ in range(10):
    l.append(float(input()))
    
l.sort(reverse = reversed)
print(l)

Si quieres orden descendente, escribe True. De lo contrario, dale a la tecla Enter: True
9
7
8
-2
-5
-9
1
3
4
5
[9.0, 8.0, 7.0, 5.0, 4.0, 3.0, 1.0, -2.0, -5.0, -9.0]


# 77. EJERCICIO : CONVIRTIENDO LOS NÚMEROS IMPARES DEL 0 AL 30 A LISTA 

Ejercicio 

Vamos a convertir los números impares del 0 al 30 a una lista y mostrar los elemento con el formato "El valor {} ocupa el índice {}

In [35]:
odd = list(range(1, 30, 2))

for i in range(len(odd)):
    print("El valor {} ocupa el índice {}".format(odd[i], i))

El valor 1 ocupa el índice 0
El valor 3 ocupa el índice 1
El valor 5 ocupa el índice 2
El valor 7 ocupa el índice 3
El valor 9 ocupa el índice 4
El valor 11 ocupa el índice 5
El valor 13 ocupa el índice 6
El valor 15 ocupa el índice 7
El valor 17 ocupa el índice 8
El valor 19 ocupa el índice 9
El valor 21 ocupa el índice 10
El valor 23 ocupa el índice 11
El valor 25 ocupa el índice 12
El valor 27 ocupa el índice 13
El valor 29 ocupa el índice 14


# 78. MATRICES CON LISTAS 

Hay un tipo muy utilizado de listas anidadas, Se caracteriza por ser una lista de m listas, donde cada una de la slistas tiene el mismo numero de elementos, n. A este tipo de listas se les conoce como matrices. 

In [11]:
matrix = [[1,2,3], [4,5,6], [7,8,9]]

Matriz. Una matriz de dimensiones m x n es una tabla formada por elementos dispuestos en m filas y n columnas. 

Los elementos de la matriz se representan con un doble subindice, aij, donde el primero indica la fila a la que pertenece y, el segundo, la columna. 

In [38]:
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Para acceder a los elementos de una matriz en python, utilizamos la sintaxis [][], donde primero indicamos la fila y , a continuación, la columna. 

In [40]:
matrix[0][2]

3

In [41]:
matrix[1][1]

5

In [42]:
matrix[2][0]

7

mostrar una matriz en python en forma de tabla con un bucle for, del siguiente modo

In [46]:
for row in matrix:
    print(row)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [45]:
for row in matrix: # Accedemos a las filas 
    for element in row:
        print(element)

1
2
3
4
5
6
7
8
9


Si lo que queremos es mostrar la matriz en forma de tabla, sin comas ni claudators por en medio, lo podemos hacer de dos formas_ 
* Haciendo uso de las dimensiones de la matriz y por tanto, de la función range()
* Sin hacer uso de las dimensiones 

la primera forma seria:

In [48]:
#m es el numero de filas que tiene la matriz.
#n el numero de columnas. 
m = len(matrix)
n = len(matrix[0])

for i in range(m):
    for j in range(n):
        print(matrix[i][j], end = " ")
    print("")

1 2 3 
4 5 6 
7 8 9 


In [13]:
print(matrix[0])
print(matrix)

[1, 2, 3]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


2da forma

In [15]:

for row in matrix: 
    for element in row: 
        print(element, end = " ")
    print("\n")
    

1 2 3 

4 5 6 

7 8 9 



## Suma de matrices 

Para poder sumasr dos matrices, necesitamos que tengan la misma dimensión. Entonces. dadas A y B dos matrices con dimension m x n, su suma será una matriz de dimensión m x n. 

In [58]:
A = [[1, 0, -3], [2, 0, 1], [-1, -1, 0]]
B = [[-1, -2, 0], [-2, 3, 0], [0, 0, -3]]

m = len(A) #numero de filas
n = len(A[0]) #numero de columnas

if len(A) == len(B) and len(A[0]) == len(B[0]):
    c = []
    
    for i in range(m):
        c.append([])
        for j in range(n): 
            c[i].append(A[i][j] + B[i][j])
    print(c)
        
else:
    print("No se puede realizar la suma, pues las dimensiones de las matrices no coinciden")

[[0, -2, -3], [0, 3, 1], [-1, -1, -3]]


In [16]:
A = [[1, 0, -3], [2, 0, 1], [-1, -1, 0]]
B = [[-1, -2, 0], [-2, 3, 0], [0, 0, -3]]

m = len(A) #numero de filas
n = len(A[0]) #numero de columnas

if len(A) == len(B) and len(A[0]) == len(B[0]):
    c = []
    
    for i in range(m):
        c.append([])
print(c)

[[], [], []]


## Producto de matrices 

Para poder multplicar matrices, necesitamos que la matriz de la izquierda tenga el mismo numero de columnas que numero de filas que tiene la matriz de la derecha. Entonces, dada las matrices A y B de dimensiones m x n y n x p respectivamente, su producto será una matriz de dimensión m x p y se obtiene del siguiente modo: 

In [26]:
A = [[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]]
B = [[-1, -2, 0], [-2, 3, 0], [0, 0, -3], [1, 1, -1]]

m, n, p = len(A), len(B), len(B[0])
C = []


for i in range(m):
    C.append([])
    for j in range(p):
        elemento = 0
        for k in range(n):
            elemento = elemento + A[i][k] * B[k][j]
        C[i].append(elemento)


In [27]:
for row in C:
    print(row)

[1, 0, 7]
[-1, -3, -4]
[1, 2, 3]


# 79.  EJERCICIO: CREANDO MANUALMENTE UNA MATRIZ DE 4X4 

Ejercicio 

Vamos a crear manualmente una matriz de tamaño 4x4 y guardalar en una lista. 

In [61]:
A = [] 
for i in range(4): 
    A.append([])
    for j in range(4):
        A[i].append(float(input("Introduce el elemento ({},{}): ".format(i, j))))
        
for i in range(4):
    for j in range(4):
        print(A[i][j], end = "  " if A[i][j] >= 0 else " ")
    print("")

Introduce el elemento (0,0): 1
Introduce el elemento (0,1): 2
Introduce el elemento (0,2): 3
Introduce el elemento (0,3): 4
Introduce el elemento (1,0): 5
Introduce el elemento (1,1): 6
Introduce el elemento (1,2): 7
Introduce el elemento (1,3): 8
Introduce el elemento (2,0): 9
Introduce el elemento (2,1): 0
Introduce el elemento (2,2): 10
Introduce el elemento (2,3): 13
Introduce el elemento (3,0): 24
Introduce el elemento (3,1): 5
Introduce el elemento (3,2): 6
Introduce el elemento (3,3): 77
1.0  2.0  3.0  4.0  
5.0  6.0  7.0  8.0  
9.0  0.0  10.0  13.0  
24.0  5.0  6.0  77.0  


In [62]:
list(range(4))

[0, 1, 2, 3]

# 80. EJERCICIO: SUMA DE MATRICES DADAS POR EL USUARIO. 

In [3]:
n = int(input("Número de filas de las matrices: "))
#Las filas siempre serán la cantidad de corchetes que haya dentro de la variable. 
m = int(input("Número de columnas de las matrices: "))

A = []
print("\n=== Matriz A ===")
for i in range(n):
    A.append([])
    for j in range(m):
        A[i].append(float(input("Introduce el elemento ({},{}: )".format(i, j))))
        
B = []
print("\n=== Matriz B ===")
for i in range(n):
    B.append([])
    for j in range(m):
        B[i].append(float(input("Introduce el elemento ({},{}: )".format(i, j))))
        
C = []
for i in range(n):
    C.append([])
    for j in range(m):
        C[i].append(A[i][j] + B[i][j])
        
print("\n=== Matriz A + B ===")
for i in range(n):
    for j in range(m):
        print(C[i][j], end = " " if C[i][j] >= 0 else " ")
    print(" ")

Número de filas de las matrices: 2
Número de columnas de las matrices: 2

=== Matriz A ===
Introduce el elemento (0,0)1
Introduce el elemento (0,1)2
Introduce el elemento (1,0)3
Introduce el elemento (1,1)4

=== Matriz B ===
Introduce el elemento (0,0)5
Introduce el elemento (0,1)6
Introduce el elemento (1,0)7
Introduce el elemento (1,1)8

=== Matriz A + B ===
6.0 8.0  
10.0 12.0  


In [4]:
A

[[1.0, 2.0], [3.0, 4.0]]

# 81. PRODUCTO DE MATRICES. 

Vamos a calcular el producto de dos matrices con listas. Ambas matrices serán dadas por el usuario asi como las dimensiones de ambas. 

In [10]:
n = int(input("Número de filas de la matriz A: "))
m = int(input("Número de columnas de la matriz A: "))
p = (int(input("Número de columnas de la matriz B: ")))

A = []
print("\n=== Matriz A ===")
for i in range(n):
    A.append([])
    for j in range(m):
        A[i].append(float(input("Introduce el elemento ({},{}): ".format(i,j))))
   
B = []
print("\n=== Matriz B ===")
for i in range(m):
    B.append([])
    for j in range(p):
        B[i].append(float(input("Introduce el elemento ({},{}): ".format(i,j))))
        
C = []
for i in range(n):
    C.append([])
    for j in range(p):
        elemento = 0
        for k in range(m):
            elemento += A[i][k] * B[k][j]
        C[i].append(elemento)
        
print("\n=== Matriz A * B ===")
for i in range(n):
    for j in range(p):
        print(C[i][j], end = "  " if C[i][j] >= 0 else " ")
    print("")
        

Número de filas de la matriz A: 2
Número de columnas de la matriz A: 3
Número de columnas de la matriz B: 2

=== Matriz A ===
Introduce el elemento (0,0): 1
Introduce el elemento (0,1): 0
Introduce el elemento (0,2): 0
Introduce el elemento (1,0): 0
Introduce el elemento (1,1): 1
Introduce el elemento (1,2): 0

=== Matriz B ===
Introduce el elemento (0,0): 3
Introduce el elemento (0,1): 2
Introduce el elemento (1,0): 0
Introduce el elemento (1,1): 1
Introduce el elemento (2,0): -1
Introduce el elemento (2,1): 0

=== Matriz A * B ===
3.0  2.0  
0.0  1.0  


In [19]:
for i in range(n):
    for j in range(p):
        print(C[i][j], end= "  " if C[i][j] >= 0 else " ")
    print("")

3.0  2.0  
0.0  1.0  


# 82. MATRICES CON NUMPY 

Existe una forma mas sencilla de trabajar con matrices y es gracias a numpy. 

In [20]:
import numpy as np 

Para crear una matriz vacía, usamos el método $\textbf{.empty()}$, al que indicamos por parametro las dimensiones. 

In [25]:
A = np.empty([2,3]) #2 filas y 3 columnas. 
A

array([[0., 0., 0.],
       [0., 0., 0.]])

Para crear una matriz vacia con las mismas dimensiones de otra matriz definida anteriomente, usamos el metodo $\textbf{.empty_like()}$, al que le indicamos por parametro la matriz existente. 

In [23]:
B = np.empty_like(A)

Para crear una matriz nula, usamos el metodo $\textbf{.zeros()}$ al que le indicamos por parametro las dimensiones 

In [22]:
C = np.zeros([2,3]) #Matriz nula de dimensiones 3 y 5. 

Para crear una matriz de ceros con las dimensiones de otra matriz definida anteriormente, usamos el metodo $\textbf{.zeros_like()}$, al que le indicamos por parametro la matriz existente. 

In [26]:
D = np.zeros_like(A) #tendra 2 filas y 3 columnas y todos sus elementos valdran 0. 
D

array([[0., 0., 0.],
       [0., 0., 0.]])

Para crear una matriz de unos, usamos el metodo $\textbf{.ones()}$ al que le indicamos por parametro las dimensiones. 

In [28]:
E = np.ones((1, 4)) #matriz de unos de dimensiones 1 x 4 
E

array([[1., 1., 1., 1.]])

Para crear una matriz de unos con las mismas dimensiones de otra matriz defininda anteriormente, usamos el metodo 
$\textbf{.ones_like()}$ al que le indicamos por parametro la matriz existente. 

In [31]:
F = np.ones_like(C)
F

array([[1., 1., 1.],
       [1., 1., 1.]])

Podemos crear matrices de numpy a partir de listas con el metodo $\textbf{.matrix()}$

In [34]:
M = np.matrix([[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]])
M

matrix([[ 1,  0, -3,  2],
        [ 2,  0,  1,  1],
        [-1,  0, -1,  0]])

Para saber las dimensiones de una matriz, podemos utilizar el metodo $\textbf{.shape()}$

In [35]:
M.shape

(3, 4)

In [39]:
A = np.matrix([[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]])
B = np.matrix([[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]])
matrixSum = A + B
matrixSum

matrix([[ 2,  0, -6,  4],
        [ 4,  0,  2,  2],
        [-2,  0, -2,  0]])

In [40]:
A.shape, B.shape

((3, 4), (3, 4))

In [41]:
#para hacer el producto matricial 
A = np.matrix([[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]])
B = np.matrix([[1, 0, -3], [2, 0, 1], [-1, 0, -1], [1,2,3]])

matrixProd = A.dot(B)
matrixProd

matrix([[ 6,  4,  6],
        [ 2,  2, -4],
        [ 0,  0,  4]])

Es mucho mas sencillo mostras una matriz en forma de tabla, pues nos basta con hacer uso de la funcion print(): 

In [42]:
print(matrixSum)
print(matrixProd)

[[ 2  0 -6  4]
 [ 4  0  2  2]
 [-2  0 -2  0]]
[[ 6  4  6]
 [ 2  2 -4]
 [ 0  0  4]]


# EJERCICIO: INTRODUCIENDO MATRIZ NxN MANUALMENTE CON NUMPY 

In [43]:
import numpy as np 

In [45]:
n = int(input("Numero de filas: "))
m = int(input("Numero de columnas: "))

A = np.empty((n,m))

for i in range(n):
    for j in range(m):
        A[i, j] = float(input("Introduce el elemento ({},{})".format(i, j)))
        
print("\n=== Matriz A ===")
print(A)

Numero de filas: 2
Numero de columnas: 3
Introduce el elemento (0,0)1
Introduce el elemento (0,1)2
Introduce el elemento (0,2)3
Introduce el elemento (1,0)4
Introduce el elemento (1,1)5
Introduce el elemento (1,2)3

=== Matriz A ===
[[1. 2. 3.]
 [4. 5. 3.]]


# Suma de matrices .


In [46]:

n = int(input("Numero de fila: "))
m = int(input("Numero de columnas: "))

A = np.empty((n, m))
print("\nMATRIZ A")

for i in range(n): 
    for j in range(m):
        A[i,j] = float(input("Introduce el elemento ({},{})".format(i,j)))
        
B = np.empty((n, m))
print("\nMATRIZ b")

for i in range(n): 
    for j in range(m):
        B[i,j] = float(input("Introduce el elemento ({},{})".format(i,j)))
        
print("\nMATRIZ A + B")
print(A+B)
        


Numero de fila: 2
Numero de columnas: 3

MATRIZ A
Introduce el elemento (0,0)1
Introduce el elemento (0,1)2
Introduce el elemento (0,2)3
Introduce el elemento (1,0)4
Introduce el elemento (1,1)5
Introduce el elemento (1,2)6

MATRIZ b
Introduce el elemento (0,0)1
Introduce el elemento (0,1)2
Introduce el elemento (0,2)3
Introduce el elemento (1,0)4
Introduce el elemento (1,1)5
Introduce el elemento (1,2)6

MATRIZ A + B
[[ 2.  4.  6.]
 [ 8. 10. 12.]]


# Multiplicacion de matrices. 

In [48]:
n = int(input("Numero de filas de A: "))
m = int(input("Numero de columnas de A: "))
p = int(input("Numero de columnas de B: "))


A = np.empty((n, m))
print("\n=== Matriz A ===")
for i in range(n):
    for j in range(m):
        A[i,j] = float(input("Introduce el elemento ({},{})".format(i,j)))
        

B = np.empty((m,p))
print("\n=== Matriz B ===")
for i in range(m):
    for j in range(p):
        B[i,j] = float(input("Introduce el elemento ({},{})".format(i,j)))
        
print("\n=== Matriz A * B ===")
print(A.dot(B))

Numero de filas de A: 3
Numero de columnas de A: 2
Numero de columnas de B: 3

=== Matriz A ===
Introduce el elemento (0,0)1
Introduce el elemento (0,1)0
Introduce el elemento (1,0)0
Introduce el elemento (1,1)1
Introduce el elemento (2,0)0
Introduce el elemento (2,1)1

=== Matriz B ===
Introduce el elemento (0,0)3
Introduce el elemento (0,1)2
Introduce el elemento (0,2)0
Introduce el elemento (1,0)1
Introduce el elemento (1,1)1
Introduce el elemento (1,2)-1

=== Matriz A * B ===
[[ 3.  2.  0.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


# EJERCICIOS 

In [15]:
#Ejercicio 1
#Crea un programa que lea una secuencia de caracteres, guarde cada caracter en una posición de una lista y
#finalmente muestre la secuencia invertida.

n = int(input("Introduce la cantidad de caracteres que quieres en la cadena: "))

l = []
for i in range(n):
    l.append(input("Introduce una letra: "))
print(l)

idx = len(l) - 1
l2 = []

while(idx>=0):
    l2.append(l[idx])
    idx = idx - 1
    
print(l2)

    

Introduce la cantidad de caracteres que quieres en la cadena: 4
Introduce una letra: a
Introduce una letra: b
Introduce una letra: c
Introduce una letra: d
['a', 'b', 'c', 'd']
['d', 'c', 'b', 'a']


In [1]:
#Ejercicio 2
#Crea un programa que lea dos strings de la misma longitud, los guarde intercalados en una lista. Por último,
#mostrar el contenido de la lista. Por ejemplo, si introducimos hola caracola y adios marieta, debería mostrarse haodleao sc
#amraarcioeltaa.

while True:
    string1 = input("Introduce una frase: ")
    string2 = input("Introduce una segunda frase: ")
    if len(string1) == len(string2):
        break
        
print(string1)
print(string2)
print("\n")

string3 = " "

for i in range(len(string1)):
    string3 =string3 + (string1[i]+string2[i])
    
print(string3)

        



Introduce una frase: Hola
Introduce una segunda frase: Casasola
Introduce una frase: Hola
Introduce una segunda frase: Flor
Hola
Flor


 HFolloar


In [3]:
#Ejercicio 3
#Crea un programa que lea un string y guarde en una lista todas las consonantes

string = input("Introduce una frase: ")
string = string.lower()

l = []
l2 = []

for i in range(len(string)):
    if string[i] == "a"or string[i] == "e" or string[i] == "i" or string[i] == "o" or string[i] == "u":
        l.append(string[i])
print("Tu frase tiene estas consonantes: {}".format(l))

for i in range(len(l)):
    if l[i] not in l2:
        l2.append(l[i])

for i in range(len(l2)):
    if l.count(l2[i]) > 1:
        print("Hay {} letras {} ".format(l.count(l2[i]),l2[i]))
    else: 
        print("Hay {} letra {}".format(l.count(l2[i]), l2[i]))

Introduce una frase: COmO yO tE Ame, jamas NADIE lO podrA imaginar U
Tu frase tiene estas consonantes: ['o', 'o', 'o', 'e', 'a', 'e', 'a', 'a', 'a', 'i', 'e', 'o', 'o', 'a', 'i', 'a', 'i', 'a', 'u']
Hay 5 letras o 
Hay 3 letras e 
Hay 7 letras a 
Hay 3 letras i 
Hay 1 letra u


In [2]:
#Ejercicio 4
#Crea un programa que lea una palabra, la guarde en una lista y compruebe si se trata de un palíndromo.
frase  = input("Introduce una palabra: ")
frase = frase.lower()
s_inv = ""
l = []
l2 = []
l3 = []

for i in range(len(frase)):
    l.append(frase[i])
    s_inv = frase[i] + s_inv
    
for i in range(len(s_inv)):
    l2.append(s_inv[i])
    
    if l[i] == l2[i]:
        l3.append(l[i])
    else:
        continue

print(l)
print("Si volteamos la palabra dice: ", end = "")
print(s_inv)
print(l2)
print("por lo tanto,", end = " ")

if l == l3 and l2 == l3:
    print("tu palabra se puede leer de adelante hacia atrás y de atrás hacia adelante.")
else:
    print("tu palabra no es palíndroma.")
    
    

    

Introduce una palabra: ferrocarril
['f', 'e', 'r', 'r', 'o', 'c', 'a', 'r', 'r', 'i', 'l']
Si volteamos la palabra dice: lirracorref
['l', 'i', 'r', 'r', 'a', 'c', 'o', 'r', 'r', 'e', 'f']
por lo tanto, tu palabra no es palíndroma.


In [100]:
#Ejercicio 5
#Crea un programa que lea una matriz 3 x 3 y devuelva el máximo de cada fila.
while True:
    n = int(input("Introduce el número de filas: "))
    m = int(input("Introduce el número de columnas: "))
    print("\n")
    if n ==3 and m == 3:
        break

A = []
print("\nMATRIZ A")
for i in range(n):
    A.append([])
    for j in range(m):
        A[i].append(float(input("Introduce el elemento ({},{}): ".format(i, j))))
    
for i in range(n):
    for j in range(m):
        print((A[i][j]), end = " ")
    print("")

l = []
menor = 999
mayor = 0
for i in range(n):
    for j in range(m):
        if A[i][j] > mayor:
            mayor = A[i][j]
        elif A[i][j] < menor:
            menor = A[i][j]
    l.append(mayor)
    j = i + 1
    print("El numero mayor de la fila {} es {}".format(j,l[i]))
    mayor = 0

Introduce el número de filas: 3
Introduce el número de columnas: 5


Introduce el número de filas: 3
Introduce el número de columnas: 3



MATRIZ A
Introduce el elemento (0,0): 1
Introduce el elemento (0,1): 6
Introduce el elemento (0,2): 5
Introduce el elemento (1,0): 5
Introduce el elemento (1,1): 5
Introduce el elemento (1,2): 8
Introduce el elemento (2,0): 9
Introduce el elemento (2,1): 7
Introduce el elemento (2,2): 2
1.0 6.0 5.0 
5.0 5.0 8.0 
9.0 7.0 2.0 
El numero mayor de la fila 1 es 6.0
El numero mayor de la fila 2 es 8.0
El numero mayor de la fila 3 es 9.0


In [12]:
#Ejercicio 6
#Crea un programa que lea un entero, n, de teclado y construya una matriz de tamaño n × n. Cada posición
#debe contener su orden en la matriz (desde 0 hasta n
#2 − 1. Por ejemplo, si n es 3, deberá crearse la matriz
#[0, 1, 2]
#[3, 4, 5]
#[6, 7, 8]

n = int(input("Introduza un número: " ))

l = []

for i in range(n):
    l.append([])
    for j in range(n):
        l[i].append(float(input("Introduzca el elemento ({},{}): ".format(i,j))))
        
for i in range(n):
    print(l[i])

Introduza un número: 2
Introduzca el elemento (0,0): 1
Introduzca el elemento (0,1): 2
Introduzca el elemento (1,0): 3
Introduzca el elemento (1,1): 4
[1.0, 2.0]
[3.0, 4.0]


In [33]:
#Ejercicio 7
#Crea una matriz de n × m y asigna los valores manualmente. El programa debe indicar si la suma de cada
#columna es el mismo valor.
n = int(input("Introduce el número de filas: "))
m = int(input("Introduce el número de columnas: "))
print(" ")
l = []
l2 = []
for i in range(n):
    l.append([])
    for j in range(m):
        l[i].append(float(input("Introduce el elemento ({},{}): ".format(i,j))))

print("\nMATRIZ A")
for i in range(n):
    for j in range(m):
        print(l[i][j], end  = " ")
    print("")
    
suma = 0 
l3 = []
l4 = []

for i in range(m):
    for j in range(n):
         suma = suma + l[j][i] 
    l2.append(suma)
    suma = 0
    
idx = 0 
idx1 = 0
for i in range(m):
    for j in range(m):
        if l2[i] == l2[j]:
            idx = idx + 1
            
             
        else:
            idx1 = idx1 + 1
            l3.append(l2[j])
            l4.append(j+1)
            
    
    if idx1 > 0:
        print("La suma de al menos una columna es diferente a las demás o todas son distintas.")
        print("La suma de la columna 1 vale {}".format(l2[0]))
        break

for i in range(len(l4)):
    if len(l4) > 1:
        print("La suma de la columna {} vale {}".format(l4[i], l3[i]))
    elif len(l4) == 1:
        print("La suma de la columna {} es la unica distinta a las demas y vale {}".format(l4[i],l3[i]))
        break

if idx == m * m:
    print("La suma de cada columna es el mismo valor.")


     

Introduce el número de filas: 4
Introduce el número de columnas: 5
 
Introduce el elemento (0,0): 1
Introduce el elemento (0,1): 2
Introduce el elemento (0,2): 3
Introduce el elemento (0,3): 4
Introduce el elemento (0,4): 5
Introduce el elemento (1,0): 6
Introduce el elemento (1,1): 7
Introduce el elemento (1,2): 8
Introduce el elemento (1,3): 9
Introduce el elemento (1,4): 10
Introduce el elemento (2,0): 11
Introduce el elemento (2,1): 12
Introduce el elemento (2,2): 13
Introduce el elemento (2,3): 14
Introduce el elemento (2,4): 15
Introduce el elemento (3,0): 16
Introduce el elemento (3,1): 17
Introduce el elemento (3,2): 18
Introduce el elemento (3,3): 19
Introduce el elemento (3,4): 20

MATRIZ A
1.0 2.0 3.0 4.0 5.0 
6.0 7.0 8.0 9.0 10.0 
11.0 12.0 13.0 14.0 15.0 
16.0 17.0 18.0 19.0 20.0 
La suma de al menos una columna es diferente a las demás o todas son distintas.
La suma de la columna 1 vale 34.0
La suma de la columna 2 vale 38.0
La suma de la columna 3 vale 42.0
La suma de la

In [99]:
# Ejercicio 8
#Crear un programa determina si la matriz introducida manualmente (tanto sus dimensiones como los elementos) 
#se trata de la matriz identidad. Recuerda que la matriz identidad debe ser una matriz cuadrada.

n = int(input("Introduce el número de filas: "))
m = int(input("Introduce el número de columnas: "))
print(" ")

l = []
l2 = []
lst = []
l3 = []
idx = 0

for i in range(n):
    l.append([])
    for j in range(m):
        l[i].append(float(input("Introduce el elemento ({},{}): ".format(i,j))))
        
for i in range(n):
    lst.append([])
    for j in range(m-1):
        lst[i].append(0)
        
if n == m:
    for i in range(n):
        l3.append([])
        if l[i][i] == 1:
            for j in range(n):
                
                if l[i][j] == 0:
                    l3[i].append(l[i][j])
                else:
                    if l[i][j] == 1:
                        continue
                    else:
                        idx = idx + 1
            if idx > 0: 
                
                break

                

                
if l3 == lst:
    print("\nTu matriz es la identidad: ")
    for i in range(n):
        for j in range(m):
            print(l[i][j], end  = " ")
        print("")
    
else:
    print("Tu matriz no es la identidad")
    for i in range(n):
        for j in range(m):
            print(l[i][j], end  = " ")
        print("")

        
                

                    
                
                
                


Introduce el número de filas: 4
Introduce el número de columnas: 4
 
Introduce el elemento (0,0): 1
Introduce el elemento (0,1): 0
Introduce el elemento (0,2): 0
Introduce el elemento (0,3): 0
Introduce el elemento (1,0): 0
Introduce el elemento (1,1): 1
Introduce el elemento (1,2): 0
Introduce el elemento (1,3): 0
Introduce el elemento (2,0): 0
Introduce el elemento (2,1): 0
Introduce el elemento (2,2): 1
Introduce el elemento (2,3): 0
Introduce el elemento (3,0): 0
Introduce el elemento (3,1): 0
Introduce el elemento (3,2): 0
Introduce el elemento (3,3): 1

Tu matriz es la identidad: 
1.0 0.0 0.0 0.0 
0.0 1.0 0.0 0.0 
0.0 0.0 1.0 0.0 
0.0 0.0 0.0 1.0 


In [48]:
###### Ejercicio 9
#Realiza un programa que calcule la matriz transpuesta.
n = int(input("Introduce el número de filas: "))
m = int(input("Introduce el número de columnas: "))
print(" ")
l = []
l2 = []

for i in range(n):
    l.append([])
    for j in range(m):
        l[i].append(float(input("Introduce el elemento ({},{}): ".format(i,j))))
        
for i in range(m):
    l2.append([])
    for j in range(n):
        l2[i].append(l[j][i])

print("\nMATRIZ A")
for i in range(n):
    for j in range(m):
        print(l[i][j], end  = " ")
    print("")

print("\n")
    
print("\nMATRIZ A TRANSPUESTA")
for i in range(m):
    for j in range(n):
        print(l[j][i], end  = " ")
    print("")
    



Introduce el número de filas: 3
Introduce el número de columnas: 4
 
Introduce el elemento (0,0): 1
Introduce el elemento (0,1): 2
Introduce el elemento (0,2): 3
Introduce el elemento (0,3): 4
Introduce el elemento (1,0): 5
Introduce el elemento (1,1): 6
Introduce el elemento (1,2): 7
Introduce el elemento (1,3): 8
Introduce el elemento (2,0): 9
Introduce el elemento (2,1): 10
Introduce el elemento (2,2): 11
Introduce el elemento (2,3): 12

MATRIZ A
1.0 2.0 3.0 4.0 
5.0 6.0 7.0 8.0 
9.0 10.0 11.0 12.0 



MATRIZ A TRANSPUESTA
1.0 5.0 9.0 
2.0 6.0 10.0 
3.0 7.0 11.0 
4.0 8.0 12.0 


In [8]:
# Ejercicio 10
#Crea un programa que pida al usuario la dimensión y cree la matriz identidad de orden correspondiente con
#numpy.


n = int(input("Introduce el número de filas: "))
m = int(input("Introduce el número de columnas: "))
print(" ")
    
        
l = []
l2 = []

for i in range(n):
    l.append([])
    for j in range(m):
        l[i].append(float(input("Introduce el elemento ({},{}): ".format(i,j))))
        
if n == m:
    for i in range(n):
        l2.append([])
        for j in range(n):
            l2[i].append(0)
        
        l2[i][i] = 1
    
    print("\nMatriz  ")
    for i in range(n):
        for j in range(n):
            print(l[i][j], end  = " ")
        print("")
    
    print("\nMatriz identidad de orden {}".format(n))
    for i in range(m):
        for j in range(n):
            print(l2[i][j], end  = " ")
        print("")
    
else:
    print("Tu matriz no es cuadrada y no tiene matriz identidad.")
    print("MATRIZ  ")
    for i in range(n):
        for j in range(m):
            print(l[i][j], end  = " ")
        print("") 




Introduce el número de filas: 4
Introduce el número de columnas: 4
 
Introduce el elemento (0,0): 1
Introduce el elemento (0,1): 2
Introduce el elemento (0,2): 3
Introduce el elemento (0,3): 4
Introduce el elemento (1,0): 5
Introduce el elemento (1,1): 6
Introduce el elemento (1,2): 7
Introduce el elemento (1,3): 8
Introduce el elemento (2,0): 9
Introduce el elemento (2,1): 10
Introduce el elemento (2,2): 11
Introduce el elemento (2,3): 12
Introduce el elemento (3,0): 13
Introduce el elemento (3,1): 14
Introduce el elemento (3,2): 15
Introduce el elemento (3,3): 16

Matriz  
1.0 2.0 3.0 4.0 
5.0 6.0 7.0 8.0 
9.0 10.0 11.0 12.0 
13.0 14.0 15.0 16.0 

Matriz identidad de orden 4
1 0 0 0 
0 1 0 0 
0 0 1 0 
0 0 0 1 


In [13]:
import pandas as pd 

regla1 = pd.read_csv("C:/Users/URIEL/Documents/DATOS (CSV,XML,JSON,ETC)/prueba.csv")

In [218]:
string = ""
dicc = {}
lista = []
for i in range(len(regla1)):
    lista.append([])
    for j in range(len(regla1.iloc[i][0])):
        string = string + regla1.iloc[i][0][j]
    string = string.split("BR_STORE_TYPE_SIZE_BFOOD")
    lista[i] = string
    string = ""
dicc["CEL_RULE"] = lista
   


In [219]:
regla1 = pd.DataFrame.from_dict(dicc)

In [220]:
regla1 = regla1[0:90]

In [221]:
regla1

CEL_RULE
0   [BR_STATE = 'BA' AND BR_CITY IN (35, 160, 780,...
1   [BR_STATE = 'BA' AND BR_CITY IN (35, 160, 780,...
2   [BR_STATE = 'BA' AND BR_CITY IN (35, 160, 780,...
3   [((BR_AREA_NIELSEN IN ('AREA I', 'AREA II', 'A...
4   [((BR_AREA_NIELSEN IN ('AREA I', 'AREA II', 'A...
..                                                ...
85              [(BR_STATE = 'AM' AND BR_CITY = 260)]
86  [BR_STATE = 'SP' AND BR_AREA_NIELSEN IN ('AREA...
87  [BR_STATE = 'SP' AND BR_AREA_NIELSEN IN ('AREA...
88  [BR_STATE = 'SP' AND BR_AREA_NIELSEN IN ('AREA...
89  [BR_STATE = 'SP' AND BR_AREA_NIELSEN IN ('AREA...

[90 rows x 1 columns]

In [222]:
regla1.to_excel('regla1.xlsx', index = False)

In [75]:
regla1 = pd.read_csv("C:/Users/URIEL/Documents/DATOS (CSV,XML,JSON,ETC)/prueba.csv")

In [78]:
string = ""




for j in range(len(regla1)):
    idx = 0
    while idx == 0:
        for i in range(len(regla1.iloc[j][0])):
            start = regla1.iloc[j][0].find("BR_STORE_TYPE_SIZE_BFOOD")
            end = regla1.iloc[j][0].find(")",start)
            if i in range(start-4,end+1):
                continue
            else:
                string = string + regla1.iloc[j][0][i]
            
        regla1.iloc[j][0] = string
        if "BR_STORE_TYPE_SIZE_BFOOD" not in regla1.iloc[j][0]:
            idx = 1
        else:
            string = ""

In [79]:
regla1.iloc[0][0]

"BR_STATE = 'BA' AND BR_CITY IN (35, 160, 780, 920, 1075, 1140, 1185, 1650, 1790, 1810, 2380, 2400, 2420, 2650, 2660, 2700, 2760, 3076) "

In [77]:
regla1.iloc[0][0]

"BR_STATE = 'BA' AND BR_CITY IN (35, 160, 780, 920, 1075, 1140, 1185, 1650, 1790, 1810, 2380, 2400, 2420, 2650, 2660, 2700, 2760, 3076) AND BR_STORE_TYPE_SIZE_BFOOD IN ('CONVENIENCE', 'SUPERETTE INDEPENDENT', 'SMALL SUPERMARKET INDEPENDENT', 'TRADITIONAL SMALL WITH CONSUMPTION', 'TRADITIONAL MEDIUM WITH CONSUMPTION', 'TRADITIONAL LARGE WITH CONSUMPTION', 'TRADITIONAL SMALL WITHOUT CONSUMPTION', 'TRADITIONAL MEDIUM WITHOUT CONSUMPTION', 'TRADITIONAL LARGE WITHOUT CONSUMPTION', 'BAKERY SMALL', 'BAKERY MEDIUM', 'BAKERY LARGE') OR BR_STORE_TYPE_SIZE_BFOOD IN ('BAR SMALL', 'BAR LARGE')"

In [74]:
regla1.to_excel('regla1.xlsx', index = False)