In [1]:
import numpy as np 

In [11]:
#Ejercicio 1
#Crea un array unidimensional de 9 elementos y transfórmalo en un array 3D. Muestra la dimensión y la
#shape antes y después del reshape

a =  np.array([1,2,3,4,5,6,7,8,9])

print(a)
print("La dimension de mi array es  {}".format(a.ndim))
print("El numero de elementos de la dimension es de {}".format(a.shape))

b = a.reshape(-1,3,3)
print(b)
print("La dimension de mi nuevo array es  {}".format(b.ndim))
print("El numero de elementos de las dimensiones del nuevo array es de {}".format(b.shape))


[1 2 3 4 5 6 7 8 9]
La dimension de mi array es  1
El numero de elementos de la dimension es de (9,)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
La dimension de mi nuevo array es  3
El numero de elementos de las dimensiones del nuevo array es de (1, 3, 3)


In [49]:
#Ejercicio 2
#Dados los arrays 2D [[-6, -5], [-4, -3], [-2, -1]] y [[1, 2], [3, 4], [5, 6]], concaténalos de
#modo que obtengas el array [[1, 2, -6, -5], [3, 4, -4, -3] [5, 6, -2, -1]].

a = np.array([[-6, -5], [-4, -3], [-2, -1]])
b = np.array([[1, 2], [3, 4], [5, 6]])


c1 = np.array([b[0],a[0]])
c2 = np.array([b[1],a[1]])
c3 = np.array([b[2],a[2]])
c1 = c1.reshape(-1)
c2 = c2.reshape(-1)
c3 = c3.reshape(-1)
c4 = np.concatenate((c1,c2))
c5 = np.concatenate((c4,c3))
c5.reshape(3,4)

array([[ 1,  2, -6, -5],
       [ 3,  4, -4, -3],
       [ 5,  6, -2, -1]])

In [63]:
#Ejercicio 3
#Dado el array 2D [[1, 2, 3], [-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]], divídelo en 3 arrays 2D.

a = np.array([[1, 2, 3], [-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]])
a = a.reshape(3,2,3)
arrays = []
for i in a:
    arrays.append(i)
    
a2 = np.array(arrays[0])
a3 = np.array(arrays[1])
a4 = np.array(arrays[2])

print(a2)
print(a3)
print(a4)

[[ 1  2  3]
 [-1  0  1]]
[[ 4  5  6]
 [-4  0  4]]
[[ 3  2  1]
 [-3  0  3]]


In [ ]:
#Ejercicio 4
#Dado el array 2D [["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato",
#"elle"]], busca las palabras que sean palíndromos.
#PISTA: Necesitarás una función universal.