La libreria Numpy provee una forma particular de array llamada "ndarray" o "Numpy Array". 



In [1]:
import numpy as np

In [2]:
Npa = np.array(range(10))
Npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
Np_ceros = np.zeros(10)
Np_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
Np_ceros = np.zeros(10, dtype=int)
Np_ceros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
Np_ones = np.ones(10)
Np_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
Np_relleno = np.full(10,256)
Np_relleno

array([256, 256, 256, 256, 256, 256, 256, 256, 256, 256])

In [7]:
#Numpy provee objeto rango
Np_rango = np.arange(10)
Np_rango

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Ndarrays con valores aleatorios y de dos dimensiones. 
Np_random_dimensiones = np.random.randint(10, size = (3,4))
Np_random_dimensiones

array([[5, 1, 0, 6],
       [9, 7, 0, 3],
       [6, 0, 0, 2]])

Reshape

Permite modificar la dimensión de un arreglo, retornando otro con distinta dimensión y forma pero manteniendo los mismos elementos. 

In [9]:
np.arange(1,65)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [10]:
#En el reshape deben ambos numeros multiplicar 64, Ej n x m = 64
Tablero_Ajedrez = np.arange(1,65).reshape(8,8)
Tablero_Ajedrez

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

Concatenación

Consiste en formar un nuevo arreglo a partir de "enganchar" o "apilar" otros. 

Con la operación
* concatenate
* vstack y hstack

In [11]:
Array1 = np.random.randint(10,size=6)
Array2 = np.random.randint(10,size=5)

Arrays_Concatenados = np.concatenate([Array1,Array2])
Arrays_Concatenados

array([9, 3, 0, 1, 3, 1, 6, 0, 6, 5, 3])

In [12]:
Array_Extra = np.array([[10],[20]])

In [13]:
#Apila verticalmente
Arrays_Apilados = np.vstack([Array_Extra,Array_Extra])
Arrays_Apilados

array([[10],
       [20],
       [10],
       [20]])

In [14]:
#Apila Horizontalmente
Arrays_Apilados = np.hstack([Array_Extra,Array_Extra])
Arrays_Apilados

array([[10, 10],
       [20, 20]])

Splitting 

Consiste en desarmar o partir los arreglos. 

Se piensa como la operación inversa a la concatenación. 

In [17]:
Array_Partido = np.split(Arrays_Concatenados, [2])
Array_Partido

[array([9, 3]), array([0, 1, 3, 1, 6, 0, 6, 5, 3])]

In [18]:
type(Array_Partido)

list

In [23]:
#Cortes verticales
T1 = np.hsplit(Tablero_Ajedrez, [4])
T1

[array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [17, 18, 19, 20],
        [25, 26, 27, 28],
        [33, 34, 35, 36],
        [41, 42, 43, 44],
        [49, 50, 51, 52],
        [57, 58, 59, 60]]),
 array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [29, 30, 31, 32],
        [37, 38, 39, 40],
        [45, 46, 47, 48],
        [53, 54, 55, 56],
        [61, 62, 63, 64]])]

In [24]:
#Cortes horizontales 
T2 = np.vsplit(Tablero_Ajedrez, [4])
T2

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])]

Agregaciones y Operaciones Vectorizadas

In [30]:
print(np.std(Tablero_Ajedrez)) #Desviacion estandar. 
print(np.var(Tablero_Ajedrez)) #Varianza
print(np.median(Tablero_Ajedrez)) #Mediana

18.472953201911167
341.25
32.5
